### ISSUE TITLE
Configuration files are in WTF format

### ISSUE THREAD

**Issue by vvo** [bpaquet/node-logstash#1]
While I do see the beauty of

`input://file:///var/log/nginx/access.log`

or

`output://zeromq://tcp://192.168.1.1:5555`

and 

`output://zeromq://tcp://192.168.1.1:5555`

Is there a reason for not using JSON:

```json
{
  "input": {
    "file": ["/var/log/nginx/access.log", "/var/log/tamere.log"],
    "zeromq": "tcp://192.168.1.1:5555"
  },
  "output": {
    "file": "/var/log/tok/tbath.log"     
  },
  "filters": {}
}
```

**Comment by moander** [comment]
+1

**Comment by bpaquet** [comment]
So I added a support for logstash config. It's not fully integrated. Missing :
* Doc
* Support of if (https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#conditionals). Complicated part is done.

Example:
````
input { file { path => '/var/log/syslog"}}
output { stdout {}}
````

Feedbacks are welcome, pull requests on doc too :)

**Comment by bpaquet** [comment]
Doc is up to date.

Feedbacks welcome :)
