### ISSUE TITLE
Project not active anymore?

### ISSUE THREAD

**Issue by Osterjour** [bpaquet/node-logstash#116]
@bpaquet are you still maintaining this project? There are pull requests which are older than a year now without any reaction from your side. I love the project and I'm thinking about a new output filter for AWS Kinesis but if this isn't maintained anymore I build something on my own which is more suitable for my use case without the aspect of being usable for multiple people within this project...
So it would be nice if you could clarify if you're still interested in pushing this forward.

Thanks!

**Comment by bpaquet** [comment]
Good question. I will clarify that next days.

**Comment by bpaquet** [comment]
Now documented in Readme.markdown. Feedbacks are welcome.
