### ISSUE TITLE
all verbs with this library?

### ISSUE THREAD

**Issue by basiclaser** [bpaquet/node-logstash#118]
I’m looking to listen to read/write/delete events from nodeJS to mongoDB - I can already detect the events, now I would like to duplicate the events from nodeJS to my elasticsearch instance. Can i use node-logstash to read/write/delete from nodeJS to elasticsearch? Thanks, I'm pretty confused at this point. (Also i dont want to use any direct streams between the database like mongo-connector)

**Comment by bpaquet** [comment]
You can use node-logstash to write to ES from NodeJS.
There are two plugins
- [elasticsearch http](https://github.com/bpaquet/node-logstash/blob/master/docs/outputs/elasticsearch.md)
- [elasticsearch zeromq](https://github.com/bpaquet/node-logstash/blob/master/docs/outputs/zeromq.md)

You can use it as external tools, or you can load node-logstash directly into your program. If you are interested by the second solution, let me know, I will write some docs.
