### ISSUE TITLE
node-logstash unable to start with a logstash's compliant config file

### ISSUE THREAD

**Issue by jerome83136** [bpaquet/node-logstash#120]
Hello,
I have installed Logstash and I'm unable to run it with that command:

`./bin/node-logstash-agent --log_level=info --log_file=/logs/logstash/node-logstash.application.log --config_file=/conf/logstash/logstash.application.conf`

But it fails with this error:

```
[Thu, 14 Apr 2016 14:56:02 GMT] INFO Log to file /logs/logstash/node-logstash.application.log , log_level info
Unable to load config file /conf/logstash/logstash.application.conf
Error: Processing error for file /conf/logstash/logstash.application.conf : Error: Parse error on line 10:
...g"    add_field => { "APPLICATION" => "
----------------------^
Expecting 'ID', 'ARRAY_START', 'VALUE', got 'START'
    at /products/node-logstash-0.0.5/lib/lib/file_loader.js:39:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

I don't now if the problem is due to a missing plugin in my node-logstash install (file-input plugin ?) or anything else ?

The line number 10 of the config file is:
add_field => { "APPLICATION" => "sfmeveryware" }

thank for your help
Regarde
Jérôme

**Comment by bpaquet** [comment]
Hi,

Can you provide your full config file ?

Regards,

Bertrand

**Comment by jerome83136** [comment]
@bpaquet Hello, you can find the config file enclosed. Regards
[logstash.sfmeveryware-samba.conf.txt](https://github.com/bpaquet/node-logstash/files/220693/logstash.sfmeveryware-samba.conf.txt)

**Comment by jerome83136** [comment]
Hello,
It seems I was using an incompatible configuration file format.

So, I have made a new configuration file by following node-logstash's instructions on Github.

Thanks for your help

Best regards
Jérôme

**Comment by bpaquet** [comment]
Yes, your file is not compatible, but should be parsable :)

**Comment by bpaquet** [comment]
Parsing is fixed. But all features are not implemented.
