### ISSUE TITLE
Creating a JSON from CSV - Filter plugin

### ISSUE THREAD

**Issue by saranya279** [bpaquet/node-logstash#128]
Need to create a JSON object from a csv. Can you please let me know how to go about this. 

For instance 
I have a row "äbc,26,07/24/86"
needs to be parsed into 

{
"name":"abc",
"age":26,
"dob":"07/24/86"
}

This data will be indexed into elasticsearch

**Comment by bpaquet** [comment]
Use the [regex](https://github.com/bpaquet/node-logstash/blob/master/docs/filters/regex.md) or [grok](https://github.com/bpaquet/node-logstash/blob/master/docs/filters/grok.md) plugin.
