### ISSUE TITLE
Can't figure out how to use node-logstash

### ISSUE THREAD

**Issue by Xeoncross** [bpaquet/node-logstash#82]
The [example seems simple enough](https://github.com/bpaquet/node-logstash#examples), however I can't seem to get it to read from the nginx log file.

I spun up a vagrant install and created this simple config `test.conf`:

    input://file:///var/log/nginx/access.log?start_index=0&use_tail=1 
    output://file:///vagrant/node-logstash/output.log 

Then I ran the bin: 

    root@vagrant-ubuntu-trusty-64:/vagrant/node-logstash/node-logstash# bin/node-logstash-agent -f /vagrant/node-logstash/test.conf 

While I see node-logstash running and waiting, the file is never created. 

~~~
[Fri, 02 Jan 2015 19:09:58 GMT] NOTICE Starting node-logstasth-agent 0.0.3 
[Fri, 02 Jan 2015 19:09:58 GMT] INFO Max http socket 100 
[Fri, 02 Jan 2015 19:09:58 GMT] INFO Loading config : 3 urls 
[Fri, 02 Jan 2015 19:09:58 GMT] INFO Initializing filter AddHost 
[Fri, 02 Jan 2015 19:09:58 GMT] INFO Initializing filter AddTimestamp 
[Fri, 02 Jan 2015 19:09:58 GMT] INFO Initializing filter AddVersion 
[Fri, 02 Jan 2015 19:09:58 GMT] INFO Config loaded. 

^C[Fri, 02 Jan 2015 19:11:39 GMT] INFO SIGINT received. 
[Fri, 02 Jan 2015 19:11:39 GMT] INFO Closing agent 
[Fri, 02 Jan 2015 19:11:39 GMT] INFO Quitting. 
~~~

**Comment by bpaquet** [comment]
As you can see in node-logstash log, there is no mention of loading your config. The ``-f``option does not exist, the correct one is ``--config_file``.
