### ISSUE TITLE
Elasticsearch output index name

### ISSUE THREAD

**Issue by megastef** [bpaquet/node-logstash#84]
Assuming an Elasticsearch system provides already an Alias and manages the time based index behind, the mechnism to specify index_prefix and generating date suffix might cause errors (and it did as time based index exists already or might change every hour instead of every day ...). 

I made a local patch to specify "index" as parameter and then it don't uses index_prefix + date. Then node-logstash is using just the index name (alias in that case) and everything works fine. 

Shall I make a pull request or would you like to provide it. My quick solution was to adapt output_elasticsearch.js instead of elastic_search_helper.js (which might be more beautiful, but I could not find out how to access config obejct there or would need to pass it).

**Comment by bpaquet** [comment]
Closed in #85.
