### ISSUE TITLE
How to provide user name and password to rubbitmq when using AMQP output

### ISSUE THREAD

**Issue by tomkregenbild** [bpaquet/node-logstash#87]
What is the parameter for providing a user name and password to rabbitmq when using the AMQP output.

I tried the following format:
output://amqp://username:password@hostname:1111

but I am getting the following error:
ERROR Error: Unable to extract port from output://amqp://username:password@hostname:1111

I guess it is caused by the ':' sign. Is that the proper way to provide a username and if so how to make the escaping work?

**Comment by bpaquet** [comment]
You can now pass username and password.
Example : output://amqp://hostname:1111?username=toto&password=titi

Not easy to make standard AMQP syntax working.
