### ISSUE TITLE
wildcard support for folders

### ISSUE THREAD

**Issue by tomkregenbild** [bpaquet/node-logstash#91]
I see in the documentation that there is a wildcard support for file names. I tried to configure a file input that has a wild card in the folder and not in the file and it seems that it is not working.

The path I tried looks like this:
/var/log/app/client_*/file.log

Is that supported in node-logstash, if not can you add such a feature?

**Comment by tomkregenbild** [comment]
Can someone update regarding this?

**Comment by bpaquet** [comment]
I will try to implement it soon.

**Comment by bpaquet** [comment]
Feedbacks are welcome :)

**Comment by tomkregenbild** [comment]
@bpaquet thanks for the help and the quick support - I just checked it and it works like a charm :)
