### ISSUE TITLE
Support wildcards in path for input plugin(File)

### ISSUE THREAD

**Issue by iemem15** [bpaquet/node-logstash#94]
Is there a Way to support wildcards in paths i.e.
/opt/weblogic/Domains/ELK_domain/servers/Managed_*/logs/Managed_?.log

It's important because the client has like 500 servers, and the domains and server names are differents.
/opt/weblogic/Domains/ELK_domain/servers/Managed_1/logs/Managed_1.log
/opt/weblogic/Domains/ELK_domain/servers/Managed_2/logs/Managed_2.log
/opt/weblogic/Domains/<Other Domains>/servers/SVR_ABC_1/logs/SVR_ABC_1.log

Thanks in advance.

**Comment by bpaquet** [comment]
No solution now, but I want to implement it soon.

**Comment by iemem15** [comment]
Thanks. In the meantime I will put all the paths.

**Comment by bpaquet** [comment]
Feedbacks are welcome :)

**Comment by iemem15** [comment]
Thanks I will test it
